server:
    servlet:
        context-path: /api
    port: 8080

spring:
    datasource:
        testing:
            jdbc-url: jdbc:postgresql://localhost:5432/testing
            username: test
            password: 1234
            driverClassName: org.postgresql.Driver
        formula: 
            jdbc-url: jdbc:postgresql://localhost:5432/formula
            username: test
            password: 1234
            driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate: 
            ddl-auto: update

management:
    endpoints:
        web:
            exposure:
                include: "*"